version: "3.8"
services:
  mysql:
    container_name: car_easy_life
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_easy_life
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    volumes:
      - data_backup:/var/lib/mysql
volumes:
  data_backup:
secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
    